services:
  db:
    image: postgres:16
    container_name: traktplus_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - trakt_db_data:/var/lib/postgresql/data
      - ./Backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "${DB_PORT}:5432"

  migrate:
    build: ./backend
    command: sh -c "python run_migrations.py"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./Backend/db/migrations:/app/db/migrations


  backend:
    build: ./backend #Backend project dircotry

    container_name: backend
    depends_on:
      - db
      - migrate
    environment:
      ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      APP_HOST: "http://localhost:${BACKEND_PORT}"
      BACKEND_PORT: "${BACKEND_PORT}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
    ports:
      - "${BACKEND_PORT}:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: "http://localhost:${BACKEND_PORT}"
    container_name: frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:80


volumes:
  trakt_db_data:

